# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7bf8a28f2435f493779d21e4ca5bba424f3c9d9f166a146fb6d1a737d5ba0f67b0a40f65585a026e6de5228b87cfe357e099860c562851009ff853a3f038c54

test:
  secret_key_base: 56e63d95767dbce17890df173df05d2003427ecf6241e545786c94c363304591a72982e1578256b50472dd4827c1aec9bd17a6179ea619ae2d7a9439fa9fbcd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
